### PR TITLE
Add async_allowed to bind and unbind method of the router

### PR DESCRIPTION
**Pull request by vaxvms**
Allow multi broker instance to bind/unbind services

### CODE REVIEW

**Comment by eruvanos** [comment]
How would you implement `get_binding` for this setup? 

The primary challenge is that with async you have to implement get_binding, which does not require service_guid. Which prevents a easy resolve for `get_binding`.

Regards

**Comment by vaxvms** [comment]
Without storing the instance_id -> broker relationship somehow, I don't know. This patch also make it work when binding is synchronous.

There is the same issue with `get_instance`

**Comment by eruvanos** [comment]
Ah I see the issue, thank you for pointing out the obvious.

**Comment by eruvanos** [comment]
@vaxvms Thank you for the PR. 

I appreciate your help.

**Pull request merged**
