### PR TITLE
Version required option

### PR DESCRIPTION
**Pull request by redorff**
I have clients who do not bother to send the "X-broker-api-version" header... so it would be nice to skip the version check when the client does not send this header.

### CODE REVIEW

**Comment by eruvanos** [comment]
Do you have examples for clients? 

In addition it would be nice if you can add your changes on top of a new branch from the eruvanos/master branch. It is way easier to check and accept pull requests if they are a separate branch.

**Comment by redorff** [comment]
apparently, a team using concourse is sending request without the X-broker-api-version header...

**Comment by eruvanos** [comment]
What do you think about adjusting not the filter itself but have it optionally not applied.

Filters are applied [here](https://github.com/eruvanos/openbrokerapi/blob/332d6ba01852fe098fa04fa179792a7e4901becf/openbrokerapi/api.py#L59).

**Comment by redorff** [comment]
Well, for clients which specify the version, I think it's the broker responsibility to check it.
If the client fails to supply the version, then it is the clients problem if the request gets misunderstood.
But, it's just my opinion! :)

**Comment by eruvanos** [comment]
Thank you for contribution.

I tweaked it a little bit [69dbc92b40ac07658952d9d1a5ccf6c8733b462e]. 
You can now disable version check by setting `DISABLE_VERSION_CHECK=true` in environment.

**Pull request closed without merging**
